### ISSUE TITLE
Creación de la función Scraper transferencias.

### ISSUE THREAD

**Issue by sstandre** [rodrigotesone1997/Analisis_Datos_Transfermarkt#1]
Issue para seguir el desarrollo de la funcion Scraper de transferencias.
El esquema a seguir es el siguiente:

### Función scraper transferencias

Dado un url (con determinadas condiciones en los botones) obtener todos los datos que aparezcan.

**Nombre de la función:**

def scraper_transferencias(url):

**Input:** 

url -> str

**Output:**
dict

url_foto -> str
nombre -> str
posicion -> str
edad -> int
nacionalidad -> str
left -> str
pais_origen -> str
pais_llegada -> str
joined -> str
fee -> float

{
“url_imagen”: url_foto ;
“nombre_completo” : nombre ;
“posicion”: posicion ;
“edad”: edad ;
“nacionalidad”: nacionalidad ;
“equipo_abandonado”: left ;
“nacionalidad_equipo_abandonado”: pais_origen ;
“nacionalidad_equipo_unido”: pais_llegada ;
“equipo_ingresado”: joined ;
“fee”: fee
}

**Comment by sstandre** [comment]
Hola @rodrigotesone1997 , te dejo unas preguntas sobre la funcion.

- Si bien el documento dice que debe devolver un diccionario, estoy levantando una tabla con varias entradas. ¿La idea es devolver una lista de diccionarios (uno para cada transferencia)? ¿ o un diccionario que tenga listas de todas las transferencias cada clave?

- La parte de nacionalidades a veces es mas de una, pensaba ponerlas en una lista. La pregunta es si cuando tienen una sola, ¿es mejor devolver una lista con un solo elemento, para ser consistentes?

- Fee: en la mayoria de los casos no hay un valor de fee, pero a veces hay un texto como "loan", "free transfer", etc. Creo que seria bueno guardarlo en otra variable, como "fee_tipo".

**Comment by rodrigotesone1997** [comment]
Buenas @sstandre , paso a responder las preguntas en orden:

1. ¡Excelente pregunta! No habia considerado ese punto que mencionas respecto a la multiplicidad de entradas.
Propongo que el output de la función sea una lista cuyos elementos sean diccionarios. En el caso de que sea una sola entrada la lista tendria un solo diccionario (lo mismo para el punto 2)
2. Exacto, cuando es una sola hace una lista de un solo elemento (va a ahorrarnos dolores de cabeza luego para no tener que discriminar entre listas y strings)
3. Yo diria de dejarlo asi (osea que pueda ser un valor numerico o string) para no complejizar el scraping. Cuando tengamos que manipularlo como dataframe en pandas va a ser bastante sencillo discriminar entre las filas con los valores que queramos ("loan", "free transfer", valores numericos o incluso rangos de valores numericos).
