### ISSUE TITLE
Funciones en archivos separados?

### ISSUE THREAD

**Issue by sstandre** [rodrigotesone1997/Analisis_Datos_Transfermarkt#2]
Esto es más que nada una pregunta para @rodrigotesone1997 sobre la organización del trabajo.

Entiendo que tenemos que dearrollar nuestras funciones en un brach propio, mi pregunta es en qué archivo incluir la función. 
¿Cada uno crea un archivo nuevo? ¿ Y luego en otro commit juntamos todo en una clase?

Originalmente habías mostrado que las distintas funcinoes de scraping iban a ser métodos de una misma clase:
![example](https://user-images.githubusercontent.com/43125375/134825594-1cb80aec-f89f-486c-ab5b-5e02346f6cea.png)
Yo me imaginé que originalmente en main ibamos a tener un archivo con el "esqueleto", es decir la clase y los nobmres de los metodos, y luego cada uno de nosotros hara un Pull Request con modificaciones al mismo archivo.

**Comment by rodrigotesone1997** [comment]
Buenas:

Excelente pregunta, la verdad olvide subir el archivo base en el cual se van a construir las funciones.
Apenas llegue a casa modifico el repositorio con ese archivo.

**Comment by sstandre** [comment]
genial!
